---
title: "Collegi elettorali 2018"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    # social: [ "twitter", "facebook", "menu" ]
    # source_code: 'https://github.com/jobonaf/dashboard-collegi'
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(knitr)
library(bubbles)
library(RColorBrewer)
load("data/dati_collegi_elettorali_2017.rda")
```


Input {.sidebar}
=======================================================================

```{r}
selectInput("comune", "scegli il Comune", choices = unique(ced$Comune), selected = sample(ced$Comune,1))
selectInput("tipo", "scegli il collegio elettorale", 
            choices = c("CameraUninominale","CameraProporzionale","SenatoUninominale","SenatoProporzionale"), 
            selected = "CameraUninominale")
```

 
```{r}
p("per le grandi città, ti può essere utile ",
actionLink("viewnext", label = "cliccare qui, per vedere le statistiche di un altro collegio"))
```


dati: [ISTAT](https://www.istat.it/it/archivio/208278)

codice: [jobonaf/dashboard-collegi](https://github.com/jobonaf/dashboard-collegi)


Comuni
=======================================================================


Column  {data-width=300}
-----------------------------------------------------------------------

```{r}
df <- reactive({
  ced %>% filter(Comune==input$comune) %>% select_(input$tipo) %>% as.data.frame()-> cu
  ced %>% rename_(Collegio=input$tipo) %>%
    filter(Collegio%in%cu[,1]) %>%
    select(Comune,Collegio,Popolazione) %>%
    group_by(Comune,Collegio) %>%
    summarise(Popolazione=sum(Popolazione)) %>%
    ungroup() %>%
    as.data.frame()
})  
```

###  {.value-box}

```{r}
renderValueBox({
  df() %>% filter(Comune==input$comune) -> pop
  valueBox(sum(pop$Popolazione),
           caption=paste("popolazione",input$comune),
           icon = "fa-users", color="info")
})
```

###  {.value-box}

```{r}
renderValueBox({
  nc <- nrow(df() %>% select(Collegio) %>% distinct())
  valueBox(nc,
           caption=c("collegio","collegi")[(nc>1)+1],
           icon = "fa-map-marker", color="success")
})
```

###  {.value-box}

```{r}
renderValueBox({
  nc <- nrow(df() %>% select(Comune) %>% distinct())
  valueBox(nc,
           caption=c("Comune","Comuni")[(nc>1)+1],
           icon = "fa-university", color="danger")
})
```

###  {.value-box}

```{r}
renderValueBox({
  valueBox(sum(df()$Popolazione),
           caption="popolazione totale",
           icon = "fa-users", color="primary")
})
```

Column
-----------------------------------------------------------------------

### {data-width=740}

```{r}
renderBubbles({
  bubbles(sqrt(df()$Popolazione), df()$Comune, 
          color = brewer.pal(n=length(unique(df()$Collegio)), "Set3")[factor(df()$Collegio)])
})
```

### {data-width=300}

```{r}
renderTable({
  df() %>%
    select(Comune,Collegio,Popolazione) %>%
    as.data.frame()
}, digits = 0)
```





Collegio
=======================================================================


Row
-----------------------------------------------------------------------

```{r}
sameColl <- reactive({
  ced %>% filter(Comune==input$comune) %>% select_(input$tipo) %>% as.data.frame()-> cu
  ced %>% rename_(Collegio=input$tipo) %>%
    mutate(sameCollege=Collegio%in%cu[,1]) %>%
    group_by(Collegio,sameCollege,Regione) %>%
    summarise(Popolazione=sum(Popolazione)) %>%
    ungroup() %>%
    as.data.frame()
})  
myColl <- reactive({
  sameColl() %>% filter(sameCollege) -> tmp
  tmp[(input$viewnext)%%nrow(tmp)+1,]
})  
statColl <- reactive({
  sameColl() %>%
    select(-sameCollege) %>%
    mutate(PopAve=mean(Popolazione),
           Delta=(Popolazione-PopAve)/PopAve*100) %>%
    arrange(Delta) %>%
    mutate(CumulPop=cumsum(Popolazione)) %>%
    group_by(Regione) %>%
    arrange(Delta) %>%
    mutate(CumulPopReg=cumsum(Popolazione))
})
```

###

```{r}
renderUI({
  h2(myColl()$Collegio)
})

```

###  {.value-box}

```{r}
renderGauge({
  p70 <- quantile(sameColl()$Popolazione,0.70)
  p85 <- quantile(sameColl()$Popolazione,0.85)
  Max <- max(sameColl()$Popolazione)
  gauge(value = myColl()$Popolazione, 
        min = min(sameColl()$Popolazione), 
        max = Max, abbreviate = F,
        sectors=gaugeSectors(warning=c(p70,p85), 
                             danger=c(p85,Max)),
        label = paste("popolazione"))
})
```

###  {.value-box}

```{r}
renderValueBox({
  ave <- mean(sameColl()$Popolazione)
  delta <- round((myColl()$Popolazione-ave)/ave*100)
  Delta <- sprintf(delta,fmt="%+i%%")
  valueBox(Delta,
           caption=paste("rispetto alla media naz."),
           icon = "fa-users", 
           color=c("success","warning","danger")[cut(abs(delta),breaks = c(0,7,15,Inf))])
})
```

Row
-----------------------------------------------------------------------

```{r}
library(ggplot2)
library(scales)
library(ggrepel)
renderPlot({
  ggplot(statColl() %>%
           mutate(isMe=myColl()$Collegio==Collegio,
                  label=ifelse(isMe,as.character(Collegio),"")), 
         aes(x=Regione, y=Delta, label=label, group=Regione, fill=Regione)) +
    geom_boxplot(colour="lightgrey", alpha=0.3) +
    coord_flip() +
    geom_point(show.legend = F, size=1.6) +
    geom_hline(yintercept = 0, linetype="dashed", color="grey") + 
    theme_bw() +
    ylab("scarto rispetto alla media naz. (%)") +
    geom_label_repel(fill="transparent") +
    scale_fill_discrete(guide=F)
}, height = 600)
```
